using ChessMaster.Application.DI;
using ChessMaster.Infrastructure;
using ChessMaster.WebAPI.Middlewares.ExceptionHandler;
using Microsoft.OpenApi.Models;

// BUILDER
var builder = WebApplication.CreateBuilder(args);

// Other User Services from other layers
builder.Services.AddApplication();
builder.Services.AddInfrastructure(builder.Configuration, builder.Host);

// CORS
builder.Services.AddCors(options =>
{
    options.AddPolicy("MyPolicy",
        corsPolicyBuilder =>
        {
            corsPolicyBuilder.AllowAnyOrigin()//.WithOrigins("localhost:3000/") // Replace with your domain
                .AllowAnyHeader()
                .AllowAnyMethod()
                .SetIsOriginAllowedToAllowWildcardSubdomains();
        });
});

// Error Handling
builder.Services.AddExceptionHandler<GlobalExceptionHandler>();
builder.Services.AddProblemDetails();

// Autogenerated Services
builder.Services.AddControllers();

builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen(
    (option) =>
    {
        option.AddSecurityDefinition("Bearer", new OpenApiSecurityScheme
        {
            In = ParameterLocation.Header,
            Description = "Please enter a valid token",
            Name = "Authorization",
            Type = SecuritySchemeType.Http,
            BearerFormat = "JWT",
            Scheme = "Bearer"
        });
        option.AddSecurityRequirement(new OpenApiSecurityRequirement
        {
            {
                new OpenApiSecurityScheme
                {
                    Reference = new OpenApiReference
                    {
                        Type=ReferenceType.SecurityScheme,
                        Id="Bearer"
                    }
                },
                new string[]{}
            }
        });
    }
);


// APP
var app = builder.Build();

// Configure the HTTP request pipeline.
if (app.Environment.IsDevelopment())
{
    app.UseSwagger();
    app.UseSwaggerUI();
}

app.UseExceptionHandler();

app.UseHttpsRedirection();

app.UseAuthentication();
app.UseAuthorization();

app.UseCors("MyPolicy");

app.MapControllers();

app.Run();